### ISSUE TITLE
Editing AltStore code

### ISSUE THREAD

**Issue by GarlicGarlic** [CrafterPika/altstore_ipas#1]
Idea: is it possible to edit the accepted bundle IDs of AltStore (using AltStore code in Riley’s Github) and install the edited version by signing it as unc0ver? Then more than one app could be installed.

**Comment by CrafterPika** [comment]
umm my problem is, i don't have an Mac to Compile iOS apps, and i don't have enough knowledge for swift

**Comment by CrafterPika** [comment]
Closing Issue due to the Repo is deprecated. Riley Testut [Released](https://twitter.com/altstoreio/status/1248726959607054337?s=20) AltStore v1.3 with sideloading support for everyone.
